---
version: 2

project_name: obsidibot

release:
  extra_files:
    - glob: ./LICENSE
  github:
    owner: USA-RedDragon
    name: obsidibot

dockers_v2:
  - images:
      - "ghcr.io/usa-reddragon/{{.ProjectName}}"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - latest
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

builds:
  - main: .
    binary: "{{.ProjectName}}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

milestones:
  - close: true
