// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type interactionsShadow struct {
	Bind *string `json:"bind" toml:"bind" yaml:"bind"`
	Port *int    `json:"port" toml:"port" yaml:"port"`
}

type ingestShadow struct {
	Bind   *string `json:"bind"   toml:"bind"   yaml:"bind"`
	Port   *int    `json:"port"   toml:"port"   yaml:"port"`
	Secret *string `json:"secret" toml:"secret" yaml:"secret"`
}

type metricsShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
	Port    *int  `json:"port"    toml:"port"    yaml:"port"`
}

type pProfShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
	Port    *int  `json:"port"    toml:"port"    yaml:"port"`
}

type databaseShadow struct {
	URL            *string `json:"url"            toml:"url"            yaml:"url"`
	MigrateOnStart *bool   `json:"migrateOnStart" toml:"migrateOnStart" yaml:"migrateOnStart"`
	MaxConns       *int    `json:"maxConns"       toml:"maxConns"       yaml:"maxConns"`
}

type discordShadow struct {
	Token         *string `json:"token"         toml:"token"         yaml:"token"`
	ApplicationID *string `json:"applicationId" toml:"applicationId" yaml:"applicationId"`
	PublicKey     *string `json:"publicKey"     toml:"publicKey"     yaml:"publicKey"`
}

type rCONShadow struct {
	Host           *string `json:"host"           toml:"host"           yaml:"host"`
	Port           *int    `json:"port"           toml:"port"           yaml:"port"`
	Password       *string `json:"password"       toml:"password"       yaml:"password"`
	TimeoutSeconds *int    `json:"timeoutSeconds" toml:"timeoutSeconds" yaml:"timeoutSeconds"`
	MaxConcurrent  *int    `json:"maxConcurrent"  toml:"maxConcurrent"  yaml:"maxConcurrent"`
}

type ratingShadow struct {
	Initial             *int `json:"initial"             toml:"initial"             yaml:"initial"`
	ProvisionalK        *int `json:"provisionalK"        toml:"provisionalK"        yaml:"provisionalK"`
	SettlingK           *int `json:"settlingK"           toml:"settlingK"           yaml:"settlingK"`
	StableK             *int `json:"stableK"             toml:"stableK"             yaml:"stableK"`
	ProvisionalGames    *int `json:"provisionalGames"    toml:"provisionalGames"    yaml:"provisionalGames"`
	SettlingGames       *int `json:"settlingGames"       toml:"settlingGames"       yaml:"settlingGames"`
	DecayGraceDays      *int `json:"decayGraceDays"      toml:"decayGraceDays"      yaml:"decayGraceDays"`
	DecayPermillePerDay *int `json:"decayPermillePerDay" toml:"decayPermillePerDay" yaml:"decayPermillePerDay"`
}

type bankShadow struct {
	CooldownSeconds *int `json:"cooldownSeconds" toml:"cooldownSeconds" yaml:"cooldownSeconds"`
	VerifyAttempts  *int `json:"verifyAttempts"  toml:"verifyAttempts"  yaml:"verifyAttempts"`
}

type leaderboardShadow struct {
	IntervalSeconds *int `json:"intervalSeconds" toml:"intervalSeconds" yaml:"intervalSeconds"`
	Size            *int `json:"size"            toml:"size"            yaml:"size"`
}

type killFeedShadow struct {
	RetentionDays *int `json:"retentionDays" toml:"retentionDays" yaml:"retentionDays"`
}

type linkShadow struct {
	CodeTTLSeconds         *int `json:"codeTTLSeconds"         toml:"codeTTLSeconds"         yaml:"codeTTLSeconds"`
	MaxAttempts            *int `json:"maxAttempts"            toml:"maxAttempts"            yaml:"maxAttempts"`
	ReissueCooldownSeconds *int `json:"reissueCooldownSeconds" toml:"reissueCooldownSeconds" yaml:"reissueCooldownSeconds"`
}

type configShadow struct {
	LogLevel     *string             `json:"logLevel"     toml:"logLevel"     yaml:"logLevel"`
	Interactions *interactionsShadow `json:"interactions" toml:"interactions" yaml:"interactions"`
	Ingest       *ingestShadow       `json:"ingest"       toml:"ingest"       yaml:"ingest"`
	Metrics      *metricsShadow      `json:"metrics"      toml:"metrics"      yaml:"metrics"`
	PProf        *pProfShadow        `json:"pprof"        toml:"pprof"        yaml:"pprof"`
	Database     *databaseShadow     `json:"database"     toml:"database"     yaml:"database"`
	Discord      *discordShadow      `json:"discord"      toml:"discord"      yaml:"discord"`
	RCON         *rCONShadow         `json:"rcon"         toml:"rcon"         yaml:"rcon"`
	Rating       *ratingShadow       `json:"rating"       toml:"rating"       yaml:"rating"`
	Bank         *bankShadow         `json:"bank"         toml:"bank"         yaml:"bank"`
	Leaderboard  *leaderboardShadow  `json:"leaderboard"  toml:"leaderboard"  yaml:"leaderboard"`
	KillFeed     *killFeedShadow     `json:"killfeed"     toml:"killfeed"     yaml:"killfeed"`
	Link         *linkShadow         `json:"link"         toml:"link"         yaml:"link"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("logLevel", configulator.LayerDefault, "default tag")
	cfg.Interactions.Port = 8080
	set("interactions.port", configulator.LayerDefault, "default tag")
	cfg.Ingest.Port = 8081
	set("ingest.port", configulator.LayerDefault, "default tag")
	cfg.Metrics.Enabled = true
	set("metrics.enabled", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9090
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.PProf.Enabled = false
	set("pprof.enabled", configulator.LayerDefault, "default tag")
	cfg.PProf.Port = 6060
	set("pprof.port", configulator.LayerDefault, "default tag")
	cfg.Database.MigrateOnStart = true
	set("database.migrateOnStart", configulator.LayerDefault, "default tag")
	cfg.Database.MaxConns = 16
	set("database.maxConns", configulator.LayerDefault, "default tag")
	cfg.RCON.Host = "127.0.0.1"
	set("rcon.host", configulator.LayerDefault, "default tag")
	cfg.RCON.Port = 7779
	set("rcon.port", configulator.LayerDefault, "default tag")
	cfg.RCON.TimeoutSeconds = 10
	set("rcon.timeoutSeconds", configulator.LayerDefault, "default tag")
	cfg.RCON.MaxConcurrent = 4
	set("rcon.maxConcurrent", configulator.LayerDefault, "default tag")
	cfg.Rating.Initial = 1200
	set("rating.initial", configulator.LayerDefault, "default tag")
	cfg.Rating.ProvisionalK = 40
	set("rating.provisionalK", configulator.LayerDefault, "default tag")
	cfg.Rating.SettlingK = 20
	set("rating.settlingK", configulator.LayerDefault, "default tag")
	cfg.Rating.StableK = 16
	set("rating.stableK", configulator.LayerDefault, "default tag")
	cfg.Rating.ProvisionalGames = 20
	set("rating.provisionalGames", configulator.LayerDefault, "default tag")
	cfg.Rating.SettlingGames = 50
	set("rating.settlingGames", configulator.LayerDefault, "default tag")
	cfg.Rating.DecayGraceDays = 30
	set("rating.decayGraceDays", configulator.LayerDefault, "default tag")
	cfg.Rating.DecayPermillePerDay = 5
	set("rating.decayPermillePerDay", configulator.LayerDefault, "default tag")
	cfg.Bank.CooldownSeconds = 10
	set("bank.cooldownSeconds", configulator.LayerDefault, "default tag")
	cfg.Bank.VerifyAttempts = 5
	set("bank.verifyAttempts", configulator.LayerDefault, "default tag")
	cfg.Leaderboard.IntervalSeconds = 60
	set("leaderboard.intervalSeconds", configulator.LayerDefault, "default tag")
	cfg.Leaderboard.Size = 20
	set("leaderboard.size", configulator.LayerDefault, "default tag")
	cfg.KillFeed.RetentionDays = 30
	set("killfeed.retentionDays", configulator.LayerDefault, "default tag")
	cfg.Link.CodeTTLSeconds = 300
	set("link.codeTTLSeconds", configulator.LayerDefault, "default tag")
	cfg.Link.MaxAttempts = 5
	set("link.maxAttempts", configulator.LayerDefault, "default tag")
	cfg.Link.ReissueCooldownSeconds = 30
	set("link.reissueCooldownSeconds", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("logLevel", configulator.LayerFile, file)
	}
	if s.Interactions != nil {
		if s.Interactions.Bind != nil {
			cfg.Interactions.Bind = *s.Interactions.Bind
			set("interactions.bind", configulator.LayerFile, file)
		}
		if s.Interactions.Port != nil {
			cfg.Interactions.Port = *s.Interactions.Port
			set("interactions.port", configulator.LayerFile, file)
		}
	}
	if s.Ingest != nil {
		if s.Ingest.Bind != nil {
			cfg.Ingest.Bind = *s.Ingest.Bind
			set("ingest.bind", configulator.LayerFile, file)
		}
		if s.Ingest.Port != nil {
			cfg.Ingest.Port = *s.Ingest.Port
			set("ingest.port", configulator.LayerFile, file)
		}
		if s.Ingest.Secret != nil {
			cfg.Ingest.Secret = *s.Ingest.Secret
			set("ingest.secret", configulator.LayerFile, file)
		}
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
		if s.PProf.Port != nil {
			cfg.PProf.Port = *s.PProf.Port
			set("pprof.port", configulator.LayerFile, file)
		}
	}
	if s.Database != nil {
		if s.Database.URL != nil {
			cfg.Database.URL = *s.Database.URL
			set("database.url", configulator.LayerFile, file)
		}
		if s.Database.MigrateOnStart != nil {
			cfg.Database.MigrateOnStart = *s.Database.MigrateOnStart
			set("database.migrateOnStart", configulator.LayerFile, file)
		}
		if s.Database.MaxConns != nil {
			cfg.Database.MaxConns = *s.Database.MaxConns
			set("database.maxConns", configulator.LayerFile, file)
		}
	}
	if s.Discord != nil {
		if s.Discord.Token != nil {
			cfg.Discord.Token = *s.Discord.Token
			set("discord.token", configulator.LayerFile, file)
		}
		if s.Discord.ApplicationID != nil {
			cfg.Discord.ApplicationID = *s.Discord.ApplicationID
			set("discord.applicationId", configulator.LayerFile, file)
		}
		if s.Discord.PublicKey != nil {
			cfg.Discord.PublicKey = *s.Discord.PublicKey
			set("discord.publicKey", configulator.LayerFile, file)
		}
	}
	if s.RCON != nil {
		if s.RCON.Host != nil {
			cfg.RCON.Host = *s.RCON.Host
			set("rcon.host", configulator.LayerFile, file)
		}
		if s.RCON.Port != nil {
			cfg.RCON.Port = *s.RCON.Port
			set("rcon.port", configulator.LayerFile, file)
		}
		if s.RCON.Password != nil {
			cfg.RCON.Password = *s.RCON.Password
			set("rcon.password", configulator.LayerFile, file)
		}
		if s.RCON.TimeoutSeconds != nil {
			cfg.RCON.TimeoutSeconds = *s.RCON.TimeoutSeconds
			set("rcon.timeoutSeconds", configulator.LayerFile, file)
		}
		if s.RCON.MaxConcurrent != nil {
			cfg.RCON.MaxConcurrent = *s.RCON.MaxConcurrent
			set("rcon.maxConcurrent", configulator.LayerFile, file)
		}
	}
	if s.Rating != nil {
		if s.Rating.Initial != nil {
			cfg.Rating.Initial = *s.Rating.Initial
			set("rating.initial", configulator.LayerFile, file)
		}
		if s.Rating.ProvisionalK != nil {
			cfg.Rating.ProvisionalK = *s.Rating.ProvisionalK
			set("rating.provisionalK", configulator.LayerFile, file)
		}
		if s.Rating.SettlingK != nil {
			cfg.Rating.SettlingK = *s.Rating.SettlingK
			set("rating.settlingK", configulator.LayerFile, file)
		}
		if s.Rating.StableK != nil {
			cfg.Rating.StableK = *s.Rating.StableK
			set("rating.stableK", configulator.LayerFile, file)
		}
		if s.Rating.ProvisionalGames != nil {
			cfg.Rating.ProvisionalGames = *s.Rating.ProvisionalGames
			set("rating.provisionalGames", configulator.LayerFile, file)
		}
		if s.Rating.SettlingGames != nil {
			cfg.Rating.SettlingGames = *s.Rating.SettlingGames
			set("rating.settlingGames", configulator.LayerFile, file)
		}
		if s.Rating.DecayGraceDays != nil {
			cfg.Rating.DecayGraceDays = *s.Rating.DecayGraceDays
			set("rating.decayGraceDays", configulator.LayerFile, file)
		}
		if s.Rating.DecayPermillePerDay != nil {
			cfg.Rating.DecayPermillePerDay = *s.Rating.DecayPermillePerDay
			set("rating.decayPermillePerDay", configulator.LayerFile, file)
		}
	}
	if s.Bank != nil {
		if s.Bank.CooldownSeconds != nil {
			cfg.Bank.CooldownSeconds = *s.Bank.CooldownSeconds
			set("bank.cooldownSeconds", configulator.LayerFile, file)
		}
		if s.Bank.VerifyAttempts != nil {
			cfg.Bank.VerifyAttempts = *s.Bank.VerifyAttempts
			set("bank.verifyAttempts", configulator.LayerFile, file)
		}
	}
	if s.Leaderboard != nil {
		if s.Leaderboard.IntervalSeconds != nil {
			cfg.Leaderboard.IntervalSeconds = *s.Leaderboard.IntervalSeconds
			set("leaderboard.intervalSeconds", configulator.LayerFile, file)
		}
		if s.Leaderboard.Size != nil {
			cfg.Leaderboard.Size = *s.Leaderboard.Size
			set("leaderboard.size", configulator.LayerFile, file)
		}
	}
	if s.KillFeed != nil {
		if s.KillFeed.RetentionDays != nil {
			cfg.KillFeed.RetentionDays = *s.KillFeed.RetentionDays
			set("killfeed.retentionDays", configulator.LayerFile, file)
		}
	}
	if s.Link != nil {
		if s.Link.CodeTTLSeconds != nil {
			cfg.Link.CodeTTLSeconds = *s.Link.CodeTTLSeconds
			set("link.codeTTLSeconds", configulator.LayerFile, file)
		}
		if s.Link.MaxAttempts != nil {
			cfg.Link.MaxAttempts = *s.Link.MaxAttempts
			set("link.maxAttempts", configulator.LayerFile, file)
		}
		if s.Link.ReissueCooldownSeconds != nil {
			cfg.Link.ReissueCooldownSeconds = *s.Link.ReissueCooldownSeconds
			set("link.reissueCooldownSeconds", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "logLevel"); ok {
		cfg.LogLevel = LogLevel(v)
		set("logLevel", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "interactions", "bind"); ok {
		cfg.Interactions.Bind = v
		set("interactions.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "interactions", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "interactions.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Interactions.Port = int(p)
		set("interactions.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "ingest", "bind"); ok {
		cfg.Ingest.Bind = v
		set("ingest.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "ingest", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ingest.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Ingest.Port = int(p)
		set("ingest.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "ingest", "secret"); ok {
		cfg.Ingest.Secret = v
		set("ingest.secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Enabled = p
		set("metrics.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Port = int(p)
		set("metrics.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Enabled = p
		set("pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Port = int(p)
		set("pprof.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "url"); ok {
		cfg.Database.URL = v
		set("database.url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "migrateOnStart"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.migrateOnStart",
				Source: n,
				Value:  v,
			}
		}
		cfg.Database.MigrateOnStart = p
		set("database.migrateOnStart", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "maxConns"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.maxConns",
				Source: n,
				Value:  v,
			}
		}
		cfg.Database.MaxConns = int(p)
		set("database.maxConns", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "discord", "token"); ok {
		cfg.Discord.Token = v
		set("discord.token", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "discord", "applicationId"); ok {
		cfg.Discord.ApplicationID = v
		set("discord.applicationId", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "discord", "publicKey"); ok {
		cfg.Discord.PublicKey = v
		set("discord.publicKey", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "host"); ok {
		cfg.RCON.Host = v
		set("rcon.host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.RCON.Port = int(p)
		set("rcon.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "password"); ok {
		cfg.RCON.Password = v
		set("rcon.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "timeoutSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.timeoutSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.RCON.TimeoutSeconds = int(p)
		set("rcon.timeoutSeconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rcon", "maxConcurrent"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.maxConcurrent",
				Source: n,
				Value:  v,
			}
		}
		cfg.RCON.MaxConcurrent = int(p)
		set("rcon.maxConcurrent", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "initial"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.initial",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.Initial = int(p)
		set("rating.initial", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "provisionalK"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.provisionalK",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.ProvisionalK = int(p)
		set("rating.provisionalK", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "settlingK"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.settlingK",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.SettlingK = int(p)
		set("rating.settlingK", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "stableK"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.stableK",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.StableK = int(p)
		set("rating.stableK", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "provisionalGames"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.provisionalGames",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.ProvisionalGames = int(p)
		set("rating.provisionalGames", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "settlingGames"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.settlingGames",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.SettlingGames = int(p)
		set("rating.settlingGames", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "decayGraceDays"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.decayGraceDays",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.DecayGraceDays = int(p)
		set("rating.decayGraceDays", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "rating", "decayPermillePerDay"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.decayPermillePerDay",
				Source: n,
				Value:  v,
			}
		}
		cfg.Rating.DecayPermillePerDay = int(p)
		set("rating.decayPermillePerDay", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "bank", "cooldownSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "bank.cooldownSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.Bank.CooldownSeconds = int(p)
		set("bank.cooldownSeconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "bank", "verifyAttempts"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "bank.verifyAttempts",
				Source: n,
				Value:  v,
			}
		}
		cfg.Bank.VerifyAttempts = int(p)
		set("bank.verifyAttempts", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "leaderboard", "intervalSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "leaderboard.intervalSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.Leaderboard.IntervalSeconds = int(p)
		set("leaderboard.intervalSeconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "leaderboard", "size"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "leaderboard.size",
				Source: n,
				Value:  v,
			}
		}
		cfg.Leaderboard.Size = int(p)
		set("leaderboard.size", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "killfeed", "retentionDays"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "killfeed.retentionDays",
				Source: n,
				Value:  v,
			}
		}
		cfg.KillFeed.RetentionDays = int(p)
		set("killfeed.retentionDays", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "link", "codeTTLSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "link.codeTTLSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.Link.CodeTTLSeconds = int(p)
		set("link.codeTTLSeconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "link", "maxAttempts"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "link.maxAttempts",
				Source: n,
				Value:  v,
			}
		}
		cfg.Link.MaxAttempts = int(p)
		set("link.maxAttempts", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "link", "reissueCooldownSeconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "link.reissueCooldownSeconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.Link.ReissueCooldownSeconds = int(p)
		set("link.reissueCooldownSeconds", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"logLevel",
		"interactions" + o.Separator + "bind",
		"interactions" + o.Separator + "port",
		"ingest" + o.Separator + "bind",
		"ingest" + o.Separator + "port",
		"ingest" + o.Separator + "secret",
		"metrics" + o.Separator + "enabled",
		"metrics" + o.Separator + "port",
		"pprof" + o.Separator + "enabled",
		"pprof" + o.Separator + "port",
		"database" + o.Separator + "url",
		"database" + o.Separator + "migrateOnStart",
		"database" + o.Separator + "maxConns",
		"discord" + o.Separator + "token",
		"discord" + o.Separator + "applicationId",
		"discord" + o.Separator + "publicKey",
		"rcon" + o.Separator + "host",
		"rcon" + o.Separator + "port",
		"rcon" + o.Separator + "password",
		"rcon" + o.Separator + "timeoutSeconds",
		"rcon" + o.Separator + "maxConcurrent",
		"rating" + o.Separator + "initial",
		"rating" + o.Separator + "provisionalK",
		"rating" + o.Separator + "settlingK",
		"rating" + o.Separator + "stableK",
		"rating" + o.Separator + "provisionalGames",
		"rating" + o.Separator + "settlingGames",
		"rating" + o.Separator + "decayGraceDays",
		"rating" + o.Separator + "decayPermillePerDay",
		"bank" + o.Separator + "cooldownSeconds",
		"bank" + o.Separator + "verifyAttempts",
		"leaderboard" + o.Separator + "intervalSeconds",
		"leaderboard" + o.Separator + "size",
		"killfeed" + o.Separator + "retentionDays",
		"link" + o.Separator + "codeTTLSeconds",
		"link" + o.Separator + "maxAttempts",
		"link" + o.Separator + "reissueCooldownSeconds",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "log verbosity: debug, info, warn, or error")
	fs.String(names[1], "", "address to listen on; empty listens on all interfaces over both IPv4 and IPv6")
	fs.Var(impl.NewInt(8080), names[2], "port the Discord interactions endpoint listens on")
	fs.String(names[3], "", "address to listen on; empty listens on all interfaces over both IPv4 and IPv6")
	fs.Var(impl.NewInt(8081), names[4], "port the game webhook endpoint listens on; must NOT be published to the internet")
	fs.String(names[5], "", "shared secret embedded in the webhook path (required); at least 32 characters, no / ? # or %; generate with openssl rand -hex 32")
	fs.Bool(names[6], true, "serve Prometheus metrics; the health probes are on the interactions listener and unaffected by this")
	fs.Var(impl.NewInt(9090), names[7], "TCP port for the metrics listener")
	fs.Bool(names[8], false, "serve pprof profiling endpoints; /debug/pprof/cmdline prints process arguments, so keep it internal")
	fs.Var(impl.NewInt(6060), names[9], "TCP port for the pprof listener")
	fs.String(names[10], "", "connection URL, e.g. postgres://user:pass@host:5432/obsidibot; psql:// and postgresql:// are accepted too")
	fs.Bool(names[11], true, "apply pending schema migrations on startup")
	fs.Var(impl.NewInt(16), names[12], "maximum PostgreSQL connections this replica's pool may open; must leave room for the background jobs and request traffic at once")
	fs.String(names[13], "", "bot token (required), used for the REST calls that post the feed and the board")
	fs.String(names[14], "", "Discord application ID (required), used to register commands and edit deferred replies")
	fs.String(names[15], "", "Ed25519 public key of the application as hex (required); every interaction is verified against it")
	fs.String(names[16], "127.0.0.1", "hostname or IP of the Source RCON server")
	fs.Var(impl.NewInt(7779), names[17], "TCP port of the Source RCON server")
	fs.String(names[18], "", "RCON password (required)")
	fs.Var(impl.NewInt(10), names[19], "deadline in seconds covering a whole RCON exchange: connect, authenticate, command, response")
	fs.Var(impl.NewInt(4), names[20], "maximum RCON commands in flight at once; further callers fail fast rather than queue")
	fs.Var(impl.NewInt(1200), names[21], "rating every player starts at")
	fs.Var(impl.NewInt(40), names[22], "K factor while a player has fewer than provisionalGames rated kills")
	fs.Var(impl.NewInt(20), names[23], "K factor between provisionalGames and settlingGames")
	fs.Var(impl.NewInt(16), names[24], "K factor once a player passes settlingGames")
	fs.Var(impl.NewInt(20), names[25], "rated games before K drops from provisionalK to settlingK")
	fs.Var(impl.NewInt(50), names[26], "rated games before K drops from settlingK to stableK")
	fs.Var(impl.NewInt(30), names[27], "days a player may be idle before decay begins")
	fs.Var(impl.NewInt(5), names[28], "thousandths of the gap to initial that an idle rating decays per day past the grace period; only ever pulls a rating down toward initial")
	fs.Var(impl.NewInt(10), names[29], "seconds a player must wait between banking operations")
	fs.Var(impl.NewInt(5), names[30], "times to re-read a player's marks trying to confirm an unverified transfer before parking it for review")
	fs.Var(impl.NewInt(60), names[31], "seconds between leaderboard message refreshes; the board and the feed share a channel rate limit, so a shorter tick starves the feed")
	fs.Var(impl.NewInt(20), names[32], "players listed on the leaderboard")
	fs.Var(impl.NewInt(30), names[33], "days to keep the raw webhook payload of a processed kill event; the event itself is kept forever")
	fs.Var(impl.NewInt(300), names[34], "seconds a link code stays valid")
	fs.Var(impl.NewInt(5), names[35], "wrong codes accepted before a challenge is burned")
	fs.Var(impl.NewInt(30), names[36], "seconds before a user may request another link code")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "logLevel"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "logLevel",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("logLevel", configulator.LayerCLI, "--"+n)
	}
	if n := "interactions" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "interactions.bind",
				Source: "--" + n,
			}
		}
		cfg.Interactions.Bind = v
		set("interactions.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "interactions" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "interactions.port",
				Source: "--" + n,
			}
		}
		cfg.Interactions.Port = v
		set("interactions.port", configulator.LayerCLI, "--"+n)
	}
	if n := "ingest" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ingest.bind",
				Source: "--" + n,
			}
		}
		cfg.Ingest.Bind = v
		set("ingest.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "ingest" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ingest.port",
				Source: "--" + n,
			}
		}
		cfg.Ingest.Port = v
		set("ingest.port", configulator.LayerCLI, "--"+n)
	}
	if n := "ingest" + o.Separator + "secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ingest.secret",
				Source: "--" + n,
			}
		}
		cfg.Ingest.Secret = v
		set("ingest.secret", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: "--" + n,
			}
		}
		cfg.PProf.Port = v
		set("pprof.port", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.url",
				Source: "--" + n,
			}
		}
		cfg.Database.URL = v
		set("database.url", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "migrateOnStart"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.migrateOnStart",
				Source: "--" + n,
			}
		}
		cfg.Database.MigrateOnStart = v
		set("database.migrateOnStart", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "maxConns"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.maxConns",
				Source: "--" + n,
			}
		}
		cfg.Database.MaxConns = v
		set("database.maxConns", configulator.LayerCLI, "--"+n)
	}
	if n := "discord" + o.Separator + "token"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "discord.token",
				Source: "--" + n,
			}
		}
		cfg.Discord.Token = v
		set("discord.token", configulator.LayerCLI, "--"+n)
	}
	if n := "discord" + o.Separator + "applicationId"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "discord.applicationId",
				Source: "--" + n,
			}
		}
		cfg.Discord.ApplicationID = v
		set("discord.applicationId", configulator.LayerCLI, "--"+n)
	}
	if n := "discord" + o.Separator + "publicKey"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "discord.publicKey",
				Source: "--" + n,
			}
		}
		cfg.Discord.PublicKey = v
		set("discord.publicKey", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.host",
				Source: "--" + n,
			}
		}
		cfg.RCON.Host = v
		set("rcon.host", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.port",
				Source: "--" + n,
			}
		}
		cfg.RCON.Port = v
		set("rcon.port", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.password",
				Source: "--" + n,
			}
		}
		cfg.RCON.Password = v
		set("rcon.password", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "timeoutSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.timeoutSeconds",
				Source: "--" + n,
			}
		}
		cfg.RCON.TimeoutSeconds = v
		set("rcon.timeoutSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := "rcon" + o.Separator + "maxConcurrent"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rcon.maxConcurrent",
				Source: "--" + n,
			}
		}
		cfg.RCON.MaxConcurrent = v
		set("rcon.maxConcurrent", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "initial"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.initial",
				Source: "--" + n,
			}
		}
		cfg.Rating.Initial = v
		set("rating.initial", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "provisionalK"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.provisionalK",
				Source: "--" + n,
			}
		}
		cfg.Rating.ProvisionalK = v
		set("rating.provisionalK", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "settlingK"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.settlingK",
				Source: "--" + n,
			}
		}
		cfg.Rating.SettlingK = v
		set("rating.settlingK", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "stableK"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.stableK",
				Source: "--" + n,
			}
		}
		cfg.Rating.StableK = v
		set("rating.stableK", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "provisionalGames"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.provisionalGames",
				Source: "--" + n,
			}
		}
		cfg.Rating.ProvisionalGames = v
		set("rating.provisionalGames", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "settlingGames"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.settlingGames",
				Source: "--" + n,
			}
		}
		cfg.Rating.SettlingGames = v
		set("rating.settlingGames", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "decayGraceDays"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.decayGraceDays",
				Source: "--" + n,
			}
		}
		cfg.Rating.DecayGraceDays = v
		set("rating.decayGraceDays", configulator.LayerCLI, "--"+n)
	}
	if n := "rating" + o.Separator + "decayPermillePerDay"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "rating.decayPermillePerDay",
				Source: "--" + n,
			}
		}
		cfg.Rating.DecayPermillePerDay = v
		set("rating.decayPermillePerDay", configulator.LayerCLI, "--"+n)
	}
	if n := "bank" + o.Separator + "cooldownSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "bank.cooldownSeconds",
				Source: "--" + n,
			}
		}
		cfg.Bank.CooldownSeconds = v
		set("bank.cooldownSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := "bank" + o.Separator + "verifyAttempts"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "bank.verifyAttempts",
				Source: "--" + n,
			}
		}
		cfg.Bank.VerifyAttempts = v
		set("bank.verifyAttempts", configulator.LayerCLI, "--"+n)
	}
	if n := "leaderboard" + o.Separator + "intervalSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "leaderboard.intervalSeconds",
				Source: "--" + n,
			}
		}
		cfg.Leaderboard.IntervalSeconds = v
		set("leaderboard.intervalSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := "leaderboard" + o.Separator + "size"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "leaderboard.size",
				Source: "--" + n,
			}
		}
		cfg.Leaderboard.Size = v
		set("leaderboard.size", configulator.LayerCLI, "--"+n)
	}
	if n := "killfeed" + o.Separator + "retentionDays"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "killfeed.retentionDays",
				Source: "--" + n,
			}
		}
		cfg.KillFeed.RetentionDays = v
		set("killfeed.retentionDays", configulator.LayerCLI, "--"+n)
	}
	if n := "link" + o.Separator + "codeTTLSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "link.codeTTLSeconds",
				Source: "--" + n,
			}
		}
		cfg.Link.CodeTTLSeconds = v
		set("link.codeTTLSeconds", configulator.LayerCLI, "--"+n)
	}
	if n := "link" + o.Separator + "maxAttempts"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "link.maxAttempts",
				Source: "--" + n,
			}
		}
		cfg.Link.MaxAttempts = v
		set("link.maxAttempts", configulator.LayerCLI, "--"+n)
	}
	if n := "link" + o.Separator + "reissueCooldownSeconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "link.reissueCooldownSeconds",
				Source: "--" + n,
			}
		}
		cfg.Link.ReissueCooldownSeconds = v
		set("link.reissueCooldownSeconds", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "logLevel":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("logLevel", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "interactions":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("interactions", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub interactionsShadow
				if err := sub.decodeJSON(dec, "interactions"); err != nil {
					return err
				}
				s.Interactions = &sub
			}
		case "ingest":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("ingest", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub ingestShadow
				if err := sub.decodeJSON(dec, "ingest"); err != nil {
					return err
				}
				s.Ingest = &sub
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, "metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, "pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "database":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("database", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub databaseShadow
				if err := sub.decodeJSON(dec, "database"); err != nil {
					return err
				}
				s.Database = &sub
			}
		case "discord":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("discord", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub discordShadow
				if err := sub.decodeJSON(dec, "discord"); err != nil {
					return err
				}
				s.Discord = &sub
			}
		case "rcon":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("rcon", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub rCONShadow
				if err := sub.decodeJSON(dec, "rcon"); err != nil {
					return err
				}
				s.RCON = &sub
			}
		case "rating":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("rating", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub ratingShadow
				if err := sub.decodeJSON(dec, "rating"); err != nil {
					return err
				}
				s.Rating = &sub
			}
		case "bank":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("bank", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub bankShadow
				if err := sub.decodeJSON(dec, "bank"); err != nil {
					return err
				}
				s.Bank = &sub
			}
		case "leaderboard":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("leaderboard", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub leaderboardShadow
				if err := sub.decodeJSON(dec, "leaderboard"); err != nil {
					return err
				}
				s.Leaderboard = &sub
			}
		case "killfeed":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("killfeed", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub killFeedShadow
				if err := sub.decodeJSON(dec, "killfeed"); err != nil {
					return err
				}
				s.KillFeed = &sub
			}
		case "link":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("link", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub linkShadow
				if err := sub.decodeJSON(dec, "link"); err != nil {
					return err
				}
				s.Link = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *interactionsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *ingestShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "secret":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Secret = &str
			default:
				return configJSONError(path+".secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *databaseShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.URL = &str
			default:
				return configJSONError(path+".url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "migrateOnStart":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.MigrateOnStart = &b
			default:
				return configJSONError(path+".migrateOnStart", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "maxConns":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".maxConns", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".maxConns", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.MaxConns = &num
			default:
				return configJSONError(path+".maxConns", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *discordShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "token":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Token = &str
			default:
				return configJSONError(path+".token", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "applicationId":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ApplicationID = &str
			default:
				return configJSONError(path+".applicationId", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "publicKey":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.PublicKey = &str
			default:
				return configJSONError(path+".publicKey", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *rCONShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Password = &str
			default:
				return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "timeoutSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".timeoutSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".timeoutSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.TimeoutSeconds = &num
			default:
				return configJSONError(path+".timeoutSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "maxConcurrent":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".maxConcurrent", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".maxConcurrent", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.MaxConcurrent = &num
			default:
				return configJSONError(path+".maxConcurrent", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *ratingShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "initial":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".initial", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".initial", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Initial = &num
			default:
				return configJSONError(path+".initial", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "provisionalK":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".provisionalK", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".provisionalK", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.ProvisionalK = &num
			default:
				return configJSONError(path+".provisionalK", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "settlingK":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".settlingK", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".settlingK", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.SettlingK = &num
			default:
				return configJSONError(path+".settlingK", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "stableK":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".stableK", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".stableK", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.StableK = &num
			default:
				return configJSONError(path+".stableK", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "provisionalGames":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".provisionalGames", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".provisionalGames", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.ProvisionalGames = &num
			default:
				return configJSONError(path+".provisionalGames", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "settlingGames":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".settlingGames", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".settlingGames", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.SettlingGames = &num
			default:
				return configJSONError(path+".settlingGames", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "decayGraceDays":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".decayGraceDays", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".decayGraceDays", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.DecayGraceDays = &num
			default:
				return configJSONError(path+".decayGraceDays", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "decayPermillePerDay":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".decayPermillePerDay", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".decayPermillePerDay", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.DecayPermillePerDay = &num
			default:
				return configJSONError(path+".decayPermillePerDay", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *bankShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "cooldownSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".cooldownSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".cooldownSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.CooldownSeconds = &num
			default:
				return configJSONError(path+".cooldownSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "verifyAttempts":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".verifyAttempts", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".verifyAttempts", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.VerifyAttempts = &num
			default:
				return configJSONError(path+".verifyAttempts", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *leaderboardShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "intervalSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".intervalSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".intervalSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.IntervalSeconds = &num
			default:
				return configJSONError(path+".intervalSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "size":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".size", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".size", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Size = &num
			default:
				return configJSONError(path+".size", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *killFeedShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "retentionDays":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".retentionDays", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".retentionDays", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.RetentionDays = &num
			default:
				return configJSONError(path+".retentionDays", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *linkShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "codeTTLSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".codeTTLSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".codeTTLSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.CodeTTLSeconds = &num
			default:
				return configJSONError(path+".codeTTLSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "maxAttempts":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".maxAttempts", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".maxAttempts", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.MaxAttempts = &num
			default:
				return configJSONError(path+".maxAttempts", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "reissueCooldownSeconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".reissueCooldownSeconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".reissueCooldownSeconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.ReissueCooldownSeconds = &num
			default:
				return configJSONError(path+".reissueCooldownSeconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "logLevel = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "interactions.bind = %v\n", c.Interactions.Bind)
	fmt.Fprintf(&b, "interactions.port = %v\n", c.Interactions.Port)
	fmt.Fprintf(&b, "ingest.bind = %v\n", c.Ingest.Bind)
	fmt.Fprintf(&b, "ingest.port = %v\n", c.Ingest.Port)
	fmt.Fprintf(&b, "ingest.secret = %v\n", c.Ingest.Secret)
	fmt.Fprintf(&b, "metrics.enabled = %v\n", c.Metrics.Enabled)
	fmt.Fprintf(&b, "metrics.port = %v\n", c.Metrics.Port)
	fmt.Fprintf(&b, "pprof.enabled = %v\n", c.PProf.Enabled)
	fmt.Fprintf(&b, "pprof.port = %v\n", c.PProf.Port)
	fmt.Fprintf(&b, "database.url = %v\n", c.Database.URL)
	fmt.Fprintf(&b, "database.migrateOnStart = %v\n", c.Database.MigrateOnStart)
	fmt.Fprintf(&b, "database.maxConns = %v\n", c.Database.MaxConns)
	fmt.Fprintf(&b, "discord.token = %v\n", c.Discord.Token)
	fmt.Fprintf(&b, "discord.applicationId = %v\n", c.Discord.ApplicationID)
	fmt.Fprintf(&b, "discord.publicKey = %v\n", c.Discord.PublicKey)
	fmt.Fprintf(&b, "rcon.host = %v\n", c.RCON.Host)
	fmt.Fprintf(&b, "rcon.port = %v\n", c.RCON.Port)
	fmt.Fprintf(&b, "rcon.password = %v\n", c.RCON.Password)
	fmt.Fprintf(&b, "rcon.timeoutSeconds = %v\n", c.RCON.TimeoutSeconds)
	fmt.Fprintf(&b, "rcon.maxConcurrent = %v\n", c.RCON.MaxConcurrent)
	fmt.Fprintf(&b, "rating.initial = %v\n", c.Rating.Initial)
	fmt.Fprintf(&b, "rating.provisionalK = %v\n", c.Rating.ProvisionalK)
	fmt.Fprintf(&b, "rating.settlingK = %v\n", c.Rating.SettlingK)
	fmt.Fprintf(&b, "rating.stableK = %v\n", c.Rating.StableK)
	fmt.Fprintf(&b, "rating.provisionalGames = %v\n", c.Rating.ProvisionalGames)
	fmt.Fprintf(&b, "rating.settlingGames = %v\n", c.Rating.SettlingGames)
	fmt.Fprintf(&b, "rating.decayGraceDays = %v\n", c.Rating.DecayGraceDays)
	fmt.Fprintf(&b, "rating.decayPermillePerDay = %v\n", c.Rating.DecayPermillePerDay)
	fmt.Fprintf(&b, "bank.cooldownSeconds = %v\n", c.Bank.CooldownSeconds)
	fmt.Fprintf(&b, "bank.verifyAttempts = %v\n", c.Bank.VerifyAttempts)
	fmt.Fprintf(&b, "leaderboard.intervalSeconds = %v\n", c.Leaderboard.IntervalSeconds)
	fmt.Fprintf(&b, "leaderboard.size = %v\n", c.Leaderboard.Size)
	fmt.Fprintf(&b, "killfeed.retentionDays = %v\n", c.KillFeed.RetentionDays)
	fmt.Fprintf(&b, "link.codeTTLSeconds = %v\n", c.Link.CodeTTLSeconds)
	fmt.Fprintf(&b, "link.maxAttempts = %v\n", c.Link.MaxAttempts)
	fmt.Fprintf(&b, "link.reissueCooldownSeconds = %v\n", c.Link.ReissueCooldownSeconds)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
